name: Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        service: ['quote_disp', 'quote_gen']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          cd ${{ matrix.service }}
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: |
          pytest -v test_app.py
      - name: Generate coverage report
        run: |
          pytest --cov=. --cov-report=xml:cov.xml test_app.py
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: cov.xml
